#!/bin/bash
#
# Cleanup script for MX Linux 
function pause(){
	read -p "$*"
}
#
#
#
#
echo This script might leave your system unusable. I made 
echo this for new installations only
echo  
#
#
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
#
#
#
# SOFTWARE REMOVAL
#
reset
echo Removing packages not required. This still leaves a 
echo running system with xorg and xfce installed. 
echo It's removing 636 packages, this may take a while.  
#
# Every package has it's own line, this makes it easier to add and remove 
# packages. It does provide a better readability. 
#
#
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
#
#
reset
#
packagelist1=(
  adobe-flash-properties-gtk
  adobe-flashplugin
  arc-theme
  arc-theme-hdpi
  arc-theme-xhdpi
  asunder
  b43-fwcutter
  baobab
  blackbird-gtk-theme
  blueman
  bluetooth
  bluez
  bluez-cups
  bluez-firmware
  bluez-obexd
  bluez-tools
  broadcom-sta-dkms
  btrfs-progs
  btrfs-tools
  bubblewrap
  cabextract
  catfish
  chromium-bsu
  chromium-bsu-data
  clementine
  clipit
  conky-all
  conky-manager
  conky-toggle-mx
  cups
  cups-browsed
  cups-bsd
  cups-client
  cups-common
  cups-core-drivers
  cups-daemon
  cups-filters
  cups-filters-core-drivers
  cups-ppdc
  cups-server-common
  disk-manager
  djvulibre-bin
  dmz-cursor-theme
  docbook-xml
  dvd+rw-tools
  eject
  elinks
  elinks-data
  emacsen-common
  faad
  faenza-cupertino-icons
  faenza-icons
  fbreader
  fbxkb
  featherpad
  feh
  ffmpeg
  file-roller
  firefox
  flac
  flake
  flatpak
  foomatic-db-compressed-ppds
  geany
  geany-common
  gimp
  gimp-data
  gmtp
  hexchat
  hexchat-common
  hplip
  hplip-data
  hyphen-en-gb
  hyphen-en-us
  icedax
  ideviceinstaller
  imagemagick
  imagemagick-6-common
  imagemagick-6.q16
  irssi
  irssi-plugin-otr
  irssi-scripts
  java-common
  lame
  laptop-detect
  lbreakout2
  lbreakout2-data
  lightning
  live-usb-cli-antix
  live-usb-maker
  luckybackup
  luckybackup-data
  mc
  mc-data
  mpg123
  mplayer
  mugshot
  mx-idevice-mounter
  mx-iphone
  mx-live-usb-maker
  nano
  nomacs
  nomacs-l10n
  normalize-audio
  nvidia-detect
  nwipe
  openconnect
  pacpl
  pdfshuffler
  peg-e
  printer-driver-brlaser
  printer-driver-c2050
  printer-driver-c2esp
  printer-driver-cjet
  printer-driver-cups-pdf
  printer-driver-dymo
  printer-driver-escpr
  printer-driver-foo2zjs
  printer-driver-foo2zjs-common
  printer-driver-gutenprint
  printer-driver-hpcups
  printer-driver-hpijs
  printer-driver-m2300w
  printer-driver-min12xxw
  printer-driver-pnm2ppa
  printer-driver-postscript-hp
  printer-driver-ptouch
  printer-driver-pxljr
  printer-driver-sag-gdi
  printer-driver-splix
  pulseaudio
  pulseaudio-module-bluetooth
  pulseaudio-utils
  python-bluez
  qpdfview
  qpdfview-djvu-plugin
  qpdfview-ps-plugin
  qpdfview-translations
  reiser4progs
  reiserfsprogs
  scrot
  simple-scan
  smtube
  sox
  speex
  swell-foop
  thunderbird
  transmission-common
  transmission-gtk
  unpaper
  ure
  vbetool
  vcdimager
  virtualbox-guest-dkms
  virtualbox-guest-utils
  virtualbox-guest-x11
  vlc
  vlc-bin
  vlc-data
  vlc-plugin-base
  vlc-plugin-qt
  vlc-plugin-video-output
  vorbis-tools
  vpnc
  vpnc-scripts
  wavpack
  wireless-tools
  wodim
  wvdial
  xfburn
  xfsprogs
  coinor-libcbc3 
  coinor-libcgl1 
  coinor-libclp1 
  coinor-libcoinmp1v5
  coinor-libcoinutils3v5 
  coinor-libosi1v5 
  conky 
  conky-std 
  dict
  foomatic-filters 
  gir1.2-gst-plugins-base-1.0 
  gir1.2-gstreamer-1.0
  gir1.2-javascriptcoregtk-4.0 
  gir1.2-soup-2.4 
  ifuse 
  kbuild 
  libabw-0.1-1
  libalut0 
  libamd2 
  libaom0 
  libappindicator1 
  libappstream-glib8 
  libaribb24-0
  libaspell15 
  libatk-wrapper-java 
  libatk-wrapper-java-jni 
  libaudclient2
  libaudio-flac-header-perl 
  libaudio-scan-perl 
  libaudiofile1 
  libavdevice57
  libbabl-0.1-0 
  libbasicusageenvironment1 
  libbit-vector-perl 
  libbluray2
  libboost-chrono1.62.0 
  libboost-date-time1.62.0 
  libboost-locale1.62.0
  libboost-thread1.62.0 
  libcamd2 
  libcarp-clan-perl 
  libccolamd2
  libcddb-get-perl 
  libcddb-perl 
  libcddb2 
  libcdr-0.1-1 libcholmod3
  libclucene-contribs1v5 
  libclucene-core1v5 
  libclutter-1.0-0
  libclutter-gtk-1.0-0 
  libcmis-0.5-5v5 
  libcogl-pango20 
  libcogl-path20
  libcogl20 
  libconfig-general-perl 
  libcrypto++6 
  libcue1 
  libcupscgi1
  libcupsmime1 
  libcupsppdc1 
  libdate-calc-perl 
  libdbusmenu-gtk4
  libdirectfb-1.2-9 
  libdjvulibre-text 
  libdjvulibre21 
  libdvbpsi10
  libe-book-0.1-1 
  libebml4v5 
  libenca0 
  libeot0 
  libetonyek-0.1-1 
  libexiv2-14
  libexporter-tiny-perl 
  libexttextcat-2.0-0 
  libexttextcat-data
  libextutils-depends-perl 
  libextutils-pkgconfig-perl 
  libfilesys-df-perl
  libfont-ttf-perl 
  libfontembed1 
  libfreehand-0.1-1 
  libfsplib0 libftgl2
  libgcab-1.0-0 
  libgee-0.8-2 
  libgegl-0.4-0 
  libgegl-common 
  libgexiv2-2
  libgimp2.0 
  libglc0 
  libgles2 
  libglewmx1.13 
  libgoo-canvas-perl
  libgoocanvas-common 
  libgoocanvas3 
  libgpgmepp6 
  libgpod4 
  libgroupsock8
  libgtk2-ex-simple-list-perl 
  libgtk2-imageview-perl 
  libgtkimageview0
  libgutenprint2 
  libharfbuzz-icu0 
  libheif1 
  libhpmud0 
  libhsqldb1.8.0-java
  libhunspell-1.6-0 
  libhyphen0 
  libimobiledevice-utils 
  libindicator7
  libio-string-perl 
  libiw30 
  libjavascriptcoregtk-4.0-18 
  libjson-c3
  liblangtag-common 
  liblangtag1 
  liblastfm1 
  liblirc-client0
  liblist-moreutils-perl 
  liblivemedia57 
  liblog-log4perl-perl 
  liblqr-1-0
  liblua5.1-0 
  liblua5.2-0 
  libmaa3 
  libmatroska6v5 
  libmetis5 
  libmicrodns0
  libmikmod3 
  libminiupnpc10 
  libmp3-tag-perl 
  libmspack0 
  libmspub-0.1-1
  libmygpo-qt1 
  libmypaint-1.3-0 
  libmypaint-common 
  libmysofa0 
  libmythes-1.2-0
  libnatpmp1 
  libneon27-gnutls 
  libodfgen-0.1-1 
  libopenconnect5
  libopenmpt-modplug1 
  libossp-uuid-perl 
  libossp-uuid16 
  libostree-1-1 
  libotr5
  libout123-0 
  libpagemaker-0.0-0 
  libparallel-forkmanager-perl 
  libpdf-api2-perl
  libplacebo4 
  libpoppler-qt5-1 
  libproc-processtable-perl 
  libprojectm2v5
  libprotobuf-lite10 
  libprotobuf10 
  libpulsedsp 
  libpython3.5 
  libqjson0
  libqpdf17 
  libqt4-network 
  libqt4-sql 
  libqt4-sql-sqlite 
  libqt5concurrent5
  libqt5script5 
  libqt5x11extras5 
  libquazip1 
  libqxt-core0 
  libqxt-gui0
  libraptor2-0 
  librarian0 
  librasqal3 
  libraw15 
  librdf0 
  libreadline5
  libreadonly-perl 
  librecode0 
  libreplaygain1 
  libresid-builder0c2a
  librevenge-0.0-0 
  libsane-hpaio 
  libsane-perl 
  libsdl-image1.2 
  libsdl-mixer1.2
  libsdl1.2debian 
  libsdl2-image-2.0-0 
  libservlet3.1-java 
  libset-intspan-perl
  libsidplay2 
  libsnmp-base 
  libsnmp30 
  libspatialaudio0 
  libspectre1 
  libstoken1
  libtiff-tools 
  libtomcrypt0 
  libtommath1 
  libtre5 
  libtry-tiny-perl 
  libumfpack5
  libunibreak1 
  libuniconf4.6 
  libupnp6 
  libusageenvironment3 
  libva-wayland2
  libvcdinfo0 
  libvlc-bin 
  libvlc5 
  libvlccore9 
  libvorbisidec1 
  libvulkan1
  libwebpmux2 
  libwmf0.2-7 
  libwpd-0.10-10 
  libwpg-0.3-3 
  libwvstreams4.6-base
  libwvstreams4.6-extras 
  libx264-155 
  libxcb-xv0 
  libxdo3 
  libxmmsclient6
  libxnvctrl0 
  libyajl2 
  libyaml-0-2 
  libzip4 
  libzlcore-data 
  libzlcore0.13
  libzltext-data 
  libzltext0.13 
  libzlui-qt4 
  musepack-tools 
  net-tools 
  pkg-config
  python-imobiledevice 
  python-plist 
  python-poppler 
  python-pypdf2 
  python3-pil
  python3-pyqt5 
  python3-reportlab 
  python3-reportlab-accel 
  python3-sip 
  realpath
  recode 
  sndfile-programs 
  socat 
  virtualbox-guest-source 
  xdg-desktop-portal
  xdg-desktop-portal-gtk 
  xdotool 
  yelp-xsl
  aisleriot
  gnome-hearts
  gnome-mahjongg
  galculator
  gtkhash
  tkhash-common
  thunar-gtkhash
  mx-clocky
  xfce4-notes
  xfce4-notes-plugin
  onboard
  onboard-common
  onboard-data
  orage
  guvcview
  libguvcview-2.0-2
  gstreamer1.0-pulseaudio
  libpulse-mainloop-glib0
  libpulse0
  libsox-fmt-pulse
  xfce4-pulseaudio-plugin
  mx-conky
  mx-conky-data
  gir1.2-appindicator3-0.1 
  gnome-cards-data 
  gstreamer1.0-plugins-good
  gstreamer1.0-plugins-ugly 
  guile-2.0-libs 
  liba52-0.7.4 
  libaa1
  libappindicator3-1 
  libasyncns0 
  libavc1394-0 
  libcaca0 
  libdbusmenu-glib4
  libdbusmenu-gtk3-4 
  libdc1394-22 
  libdca0 
  libde265-0 
  libdv4 
  libdvdnav4
  libdvdread4 
  libfaad2 
  libgc1c2 
  libgsl2 
  libgstreamer-plugins-bad1.0-0
  libgtkmm-3.0-1v5 
  libhunspell-1.4-0 
  libical2 
  libiec61883-0 
  libilmbase12
  libindicator3-7 
  libjack-jackd2-0 
  libkate1 
  libkeybinder-3.0-0 
  liblilv-0-0
  libmad0 
  libmhash2 
  libmjpegutils-2.1-0 
  libmms0 
  libmodplug1 
  libmpcdec6
  libmpeg2-4 
  libmpeg2encpp-2.1-0 
  libmplex2-2.1-0 libofa0 
  libopenal-data
  libopenal1 
  libopencv-calib3d2.4v5 
  libopencv-features2d2.4v5
  libopencv-flann2.4v5 
  libopencv-highgui2.4-deb0 
  libopencv-objdetect2.4v5
  libopencv-video2.4v5 
  libopenexr22 
  libpango1.0-0 
  libpangox-1.0-0
  libportaudio2 
  libqt4-dbus 
  libqt4-opengl 
  libqt4-xml 
  libqtcore4 
  libqtdbus4
  libqtgui4 
  libraw1394-11 
  libsbc1 
  libserd-0-0 
  libshout3 
  libsidplay1v5
  libsord-0-0 
  libsoundtouch1 
  libsox-fmt-mp3 
  libspandsp2 
  libspeexdsp1
  libsratom-0-0 
  libsrtp0 
  libtag1v5 
  libtag1v5-vanilla 
  libunique-1.0-0 
  libv4l-0
  libv4lconvert0 
  libvo-aacenc0 
  libvo-amrwbenc0 
  libwebrtc-audio-processing1
  libwildmidi-config 
  libwildmidi2 
  libx265-95 
  libzbar0 
  mx17-artwork
  phonon-backend-gstreamer-common 
  python-rsvg 
  python3-gi-cairo 
  qdbus 
  qtchooser
  papirus-icon-theme
  gnome-icon-theme
  gdebi
  gir1.2-vte-2.91
  tango-icon-theme
  tumbler-plugins-extra
  gvfs-backends
  gstreamer1.0-libav 
  libffmpegthumbnailer4v5
  libavfilter6
  gnome-schedule
  thunar-archive-plugin
  python-gnome2
  libavformat57 
  libchromaprint1 
  libavcodecs57
  system-config-printer
  libswresample2
  libswresample3
  libpostproc54
  system-config-printer-common 
  ghostscript-x 
  psutils
  ghostscript
  mx-snapshot
  system-config-printer-udev
  libgs9
  python3-cups-helpers
  mx-tweak
  mx-tweak-data 
  cli-installer-antix 
  desktop-defaults-xfce-mx17 
  xfce4-messenger-plugin 
  at 
  gir1.2-notify-0.7 
  gir1.2-packagekitglib-1.0 
  libass5 
  libavutil55 
  libbs2b0
  libcdio-cdda1 
  libcdio-paranoia1 
  libcrystalhd3 
  libcupsfilters1 
  libcupsimage2
  libfftw3-double3 
  libflite1 
  libgdata-common 
  libgdata22 
  libgme0 
  libgoa-1.0-0b
  libgoa-1.0-common 
  libgs9-common 
  libgsf-1-114 
  libgsf-1-common 
  libidl-2-0
  libijs-0.35 
  libjbig2dec0 
  libmp3lame0 
  libmpg123-0 
  libnfs8 
  libnuma1 
  liboauth0
  libopencv-core2.4v5 
  libopencv-imgproc2.4v5 
  libopenmpt0 
  libopenraw1v5
  libopenrawgnome1v5 
  liborbit2 
  libpackagekit-glib2-18 
  libpaper-utils 
  libpaper1
  libpgm-5.2-0 
  librubberband2 
  libshine3 
  libsnappy1v5 
  libsodium18 
  libsoxr0
  libspeex1 
  libssh-gcrypt-4 
  libswscale4 
  libtbb2 
  libtwolame0 
  libva-drm2
  libva-x11-2 
  libvpx4 
  libwebpmux3 
  libx264-148 
  libx265-146 
  libxvidcore4 
  libzmq5
  libzvbi-common 
  libzvbi0 
  mx-iso-template 
  python-gconf 
  python-pyorbit
  python3-cairo 
  python3-cups 
  python3-dbus 
  python3-pexpect 
  python3-ptyprocess
  python3-requests 
  python3-urllib3
)
sudo apt-get -y remove ${packagelist1[@]}
echo Again to be sure 
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
sudo apt-get -y remove ${packagelist1[@]}
#
#
reset
#
#
#
# INSTALLATION
#
echo Let's install some tools 
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
#
#
packagelist2=(
  ncdu
  localepurge
)
sudo apt-get -y install ${packagelist2[@]}
#
reset
#
echo No more apt changes, let's clean, autoclean 
echo and autoremove just in case. 
#
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
apt-get clean
apt-get autoclean
apt-get autoremove -y 
#
#
#
#
# REMOVING UNUSED LOCALES
#
#
echo Let's clean locales. 
# The echo's create a new document that localepurge 
# uses to keep the locales you actually need. 
#
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
echo MANDELETE > /etc/locale.nopurge
echo SHOWFREEDSPACE >> /etc/locale.nopurge
echo QUICKNDIRTYCALC  >> /etc/locale.nopurge
echo VERBOSE >> /etc/locale.nopurge
echo en_US >> /etc/locale.nopurge
echo EN_US.UTF-8 >> /etc/locale.nopurge
#
#
# We can now remove the unneeded locales
#
localepurge
#
#
#
#
# REMOVING UNNEEDED FILES
#
#
#
# We don't need backgrounds images.
#
Echo remove backgrounds
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
rm /user/share/backgrounds/*.jpg 
rm /user/share/backgrounds/*.txt
rm /user/share/backgrounds/*.png
rm /user/share/backgrounds/*.JPG
rm /user/share/backgrounds/default_wallpaper_attribution
rm -rf /usr/share/backgrounds/MXLinux
rm -rf /usr/share/backgrounds/xfce
#
#
#
#
# CHANGING THE RUNLEVEL
#
# Let's change the runlevel to runlevel 3 to boot in multi 
# user mode with networking, but without a graphical environment. 
#
echo Let's set runlevel 3 
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
sed -i 's/id:5/id:3/g' /etc/inittab 
#
#
#
#
# DISABLING THE BOOT SCREEN
#
#
# I don't like graphical boot screens. Makes it more difficult 
# to see a problem. We left xorg because this makes it possible 
# to still start the GUI. After logging in, type the following 
# command to start the graphical environment: startx
#
echo Last thing, let's remove the graphical boot 
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
sed -i 's/quiet splash//' /etc/default/grub
#
# Update grub to make sure the previous setting sticks
#
update-grub
#
#
#
echo All done, time for a reboot!
pause 'Press [Enter] key to continue... or Ctrl+C to abort'
reboot

